tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "aspell"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "chezmoi"
# To build libgit
brew "cmake"
brew "coreutils"
brew "curl"
brew "fd"
brew "ffmpeg" # used by youtube-dl
brew "gcc"
brew "gnutls"
brew "git"
brew "htop"
brew "jq"
# Mac App Store command-line util
brew "mas"
brew "leiningen"
# For the system Java wrappers to find this JDK, symlink it with
#  sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
brew "openjdk@11"
brew "pass"
brew "restic"
brew "ripgrep"
brew "rustup-init"
brew "shellcheck"
brew "sk"
brew "starship"
brew "tectonic"
brew "terminal-notifier"
brew "tmux"
brew "tokei"
brew "tree"
brew "vim"
brew "youtube-dl"
brew "borkdude/brew/babashka"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "d12frosted/emacs-plus/emacs-plus@28"

## Services
brew "postgresql@13", restart_service: :changed, link: true
brew "redis", restart_service: :changed

cask "aerial"
cask "alacritty"
cask "anybar"
cask "calibre"
cask "dash"
cask "discord"
cask "font-et-book"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "gpg-suite" # gpg-tools
cask "jetbrains-toolbox"
cask "keybase"
cask "mattermost"
cask "monitorcontrol"
cask "obsidian"
cask "openaudible"
cask "plexamp"
cask "proxyman"
cask "syncthing"
cask "vlc"
cask "wireshark"
cask "zotero"
